### ISSUE TITLE
Derive Debug more often?

### ISSUE THREAD

**Issue by holtgrewe** [anergictcell/hpo#37]
Thank you for this useful and great library.

What about introducing a `#[derive(Debug)]` in more places? For example, in `Builtins`, this would allow for serde deserialization with a custom deserializer.

**Comment by anergictcell** [comment]
Hi, thanks for the feedback. Definitely something I can and will do. It's easy to add and makes total sense. I had no idea the `Debug` trait is needed for Serde, but good to know and keep in mind. 
Feel free to open a PR if you need this urgently, I don't know when I'll be able to add it myself

**Comment by anergictcell** [comment]
Thanks a lot for the improvement!
